Prevent user from sending negative sol
usedispatch/dispatch-forum-npm-package pull request #167
Opened 2022-09-29 14:18 UTC by ana2201

## Description
Prevent the user from sending negative SOL

### Preview
https://forum-staging-flliae9yb-usedispatch.vercel.app/

https://www.loom.com/share/e6e5af154f75422f870e6207cb806967

2022-09-29 16:44 UTC, zfaizal2 requested changes

2022-09-29 16:44 UTC, zfaizal2 commented on src/components/forums/topic/GiveAward.tsx
>                  name="award"
can you replace this component with the Input.tsx component as well in `components/common`

2022-09-30 00:35 UTC, viksit commented
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/198669/193165334-bb64e46b-a561-4281-a158-94c6ad5c1c77.png">


I can go in to the form, put cursor in
press left arrow
add -1

solution: make sure the button to send does not activate if value in form is negative.

2022-09-30 13:56 UTC, zfaizal2 commented on .eslintrc.json
> +        "@typescript-eslint/strict-boolean-expressions": [
we should leave this rule on and continue to do null checks manually.

2022-09-30 13:56 UTC, zfaizal2 commented on src/components/common/Input.tsx
> +        step={type === 'number' ? step ?? 'any' : undefined}
what is this meant to do?

2022-09-30 17:19 UTC, zfaizal2 approved these changes

2022-09-30 17:21 UTC, merged