Remove spinner step
usedispatch/dispatch-forum-npm-package pull request #168
Opened 2022-09-29 19:19 UTC by ana2201

## Description
Don't show so many spinners, just show the 'posting' step and the success notification as confirmation

## Screenshots

2022-09-30 00:38 UTC, viksit commented
this looks good function wise.

- "Replace "posting" status in the post with "Confirming on chain"
- lets put that transaction ID we used to have in that same area with a chain ⛓ icon.
- once the post is done, replace "confirming on chain" with "confirmed"

2022-09-30 15:59 UTC, ana2201 commented
@viksit I added a small spinner in the buttons when awaiting for the user approval

- https://www.loom.com/share/abcd2865ef004e7f9813f73b160b1419
- https://www.loom.com/share/fd5151a73684426a9ec31272c7b05eb1

2022-10-05 17:38 UTC, zfaizal2 requested changes

2022-10-05 17:38 UTC, zfaizal2 commented on src/components/forums/topic/TopicContent.tsx
> +  const [addingAccessToken, setAddingAccessToken] = useState(false);
same as above

2022-10-06 15:44 UTC, zfaizal2 commented
noticed a bug where when creating a reply, two replies show up in the UI. 
![image](https://user-images.githubusercontent.com/3940879/194358116-72422383-8f49-499e-ba86-4ffc5577d4be.png)

2022-10-06 17:17 UTC, ana2201 commented
> noticed a bug where when creating a reply, two replies show up in the UI. ![image](https://user-images.githubusercontent.com/3940879/194358116-72422383-8f49-499e-ba86-4ffc5577d4be.png)

oh, good catch! the order in which the replies and text area are shown were changed after this PR was opened, so when that was merged, the block ended up duplicated here 🙃

It's working fine now
![image](https://user-images.githubusercontent.com/47254484/194377351-082535d9-d94e-44fc-96c3-06beebacf456.png)

2022-10-07 13:00 UTC, merged