New create topic flow
usedispatch/dispatch-forum-npm-package pull request #191
Opened 2022-10-19 17:21 UTC by ana2201

## Description
- Remove the big spinner currently shown when creating a new topic
- show the new topic in the list with a 'confirming' label
- redirect to new topic page once the tx is confirmed

## Screenshots
- preview link---> https://forum-staging-p47rdtk8v-usedispatch.vercel.app/

![image](https://user-images.githubusercontent.com/47254484/196760862-dadb705c-f5c3-4875-a5f1-06b938a64885.png)

2022-10-19 17:56 UTC, ana2201 commented on .eslintrc.json
> +                "default": "array"
Changes this so that we could define arrays like `const x: string[] = ['a', 'b'];`

2022-10-19 19:37 UTC, zfaizal2 commented
I no longer see the revised "create forum" flow here, and I'm held up on this loading button until forum is created 
![image](https://user-images.githubusercontent.com/3940879/196787357-509c85bf-f9a0-4f98-82db-663b677f31aa.png)

2022-10-19 19:56 UTC, zfaizal2 requested changes
mainly the comment above, I'll rereview it entirely once that's resolved

2022-10-20 13:52 UTC, ana2201 commented
> I no longer see the revised "create forum" flow here, and I'm held up on this loading button until forum is created ![image](https://user-images.githubusercontent.com/3940879/196787357-509c85bf-f9a0-4f98-82db-663b677f31aa.png)

Solved 🙂  the `useMemo` on forumContent was missing a dependency

2022-10-21 14:35 UTC, diegorosolino approved these changes

2022-10-24 16:54 UTC, zfaizal2 approved these changes

2022-10-24 17:01 UTC, merged